version: '3'
services:
  python-api:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - dashboard-network
    restart: on-failure
    ports:
      - 8081:8081
      
networks:
  dashboard-network:
    external: true
