version: '3'
services:
  api-python:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8081:8081
    volumes:
      - .:/app
    networks:
      - dashboard-network

networks:
  dashboard-network:
    external:
      name: dashboard-network