version: '3'
services:
  api-python:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8081:8081
    volumes:
      - .:/app
    environment:
      - REDIS_HOST=localhost
      - REDIS_PORT=6379