version: '3'
services:
  api-python:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8081:8081
    volumes:
      - .:/app
    networks:
      - dashboard-network
    x-develop:
      watch:
        - action: sync
          path: ./app
          target: /app/app
          ignore:
            - node_modules/
        - action: rebuild
          path: package.json

networks:
  dashboard-network:
    name: dashboard-network