version: '3'
services:
  redis:
    image: redis:latest
    ports:
      - 6379:6379
  python-server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    volumes:
      - .:/app
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
