name: Deploy to ECR and EC2

on:
  push:
    branches: 
      - main

env:
  AWS_REGION: sa-east-1
  AWS_ECR_REPO: 548673342488.dkr.ecr.sa-east-1.amazonaws.com/pyboard-api
  SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_PRIVATE_KEY }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up AWS CLI
        run: |
          sudo apt-get install -y awscli
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure set region ${{ env.AWS_REGION }}

      - name: Login to AWS ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and push Docker image to ECR
        run: |
          docker build -t ${{ env.AWS_ECR_REPO }} .
          docker tag ${{ env.AWS_ECR_REPO }}:latest ${{ env.AWS_ECR_REPO }}:${{ github.sha }}
          docker push ${{ env.AWS_ECR_REPO }}:${{ github.sha }}
          docker tag ${{ env.AWS_ECR_REPO }}:${{ github.sha }} ${{ env.AWS_ECR_REPO }}:latest
          docker push ${{ env.AWS_ECR_REPO }}:latest

      - name: SSH into EC2 instance and deploy container
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_SSH_HOST }}
          username: ${{ secrets.EC2_SSH_USERNAME }}
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          script: |
            docker --version